apiVersion: v1
kind: PersistentVolumeClaim  #the databases is not persistent by default, 
metadata: 
  name: mongo-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi